name: Build CMake for Android 32-bit

on:
  workflow_dispatch:

jobs:
  build-cmake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout CMake source
      uses: actions/checkout@v3
      with:
        repository: Kitware/CMake
        path: cmake-src

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26b

    - name: Configure Environment
      run: |
        export NDK=$ANDROID_NDK_ROOT
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
        export TARGET=armv7a-linux-androideabi
        export API=21
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++

        mkdir build
        cd build
        cmake ../cmake-src \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_SYSTEM_VERSION=$API \
          -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
          -DCMAKE_ANDROID_NDK=$NDK \
          -DCMAKE_SYSTEM_PROCESSOR=armv7-a \
          -DCMAKE_C_COMPILER=$CC \
          -DCMAKE_CXX_COMPILER=$CXX \
          -DCMAKE_INSTALL_PREFIX=$PWD/install

    - name: Build & Install CMake
      run: |
        cd build
        make -j4
        make install

    - name: Upload compiled CMake binary
      uses: actions/upload-artifact@v3
      with:
        name: cmake-android32
        path: build/install/bin/