name: Build CMake for Android 32-bit (final)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build cmake git python3

    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Clone CMake source
      run: |
        git clone --depth=1 https://github.com/Kitware/CMake.git cmake-src

    - name: Create dummy android_lf.h
      run: |
        mkdir -p cmake-src/Utilities/cmlibarchive/contrib/android/include
        echo "// dummy android_lf.h" > cmake-src/Utilities/cmlibarchive/contrib/android/include/android_lf.h
        echo "#pragma once" >> cmake-src/Utilities/cmlibarchive/contrib/android/include/android_lf.h
        echo "#define ANDROID_LF_FAKE" >> cmake-src/Utilities/cmlibarchive/contrib/android/include/android_lf.h

    - name: Patch uv_available_parallelism() safely
      run: |
        FILE="cmake-src/Utilities/cmlibuv/src/unix/core.c"
        awk '
          BEGIN { replaced = 0 }
          /unsigned int uv_available_parallelismvoid/ {
            print "#ifdef __ANDROID__"
            print "unsigned int uv_available_parallelism(void) { return 1; }"
            print "#else"
            skip = 1
            next
          }
          /return unsigned rc;/ && skip {
            print "#endif"
            skip = 0
            replaced = 1
            next
          }
          { if (!skip) print }
          END { if (!replaced) exit 1 }
        ' "$FILE" > "$FILE.patched" && mv "$FILE.patched" "$FILE"

    - name: Set environment for ARMv7a
      run: |
        echo "TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64" >> $GITHUB_ENV
        echo "TARGET=armv7a-linux-androideabi" >> $GITHUB_ENV
        echo "API=21" >> $GITHUB_ENV

    - name: Configure & Build CMake
      run: |
        export CC=$TOOLCHAIN/bin/${TARGET}${API}-clang
        export CXX=$TOOLCHAIN/bin/${TARGET}${API}-clang++

        mkdir build && cd build
        cmake ../cmake-src \
          -DCMAKE_SYSTEM_NAME=Android \
          -DCMAKE_SYSTEM_VERSION=$API \
          -DCMAKE_ANDROID_ARCH_ABI=armeabi-v7a \
          -DCMAKE_ANDROID_NDK=$ANDROID_NDK_ROOT \
          -DCMAKE_SYSTEM_PROCESSOR=armv7-a \
          -DCMAKE_C_COMPILER=$CC \
          -DCMAKE_CXX_COMPILER=$CXX \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=$PWD/install \
          -G Ninja

        ninja
        ninja install

    - name: Upload compiled CMake (Android 32-bit)
      uses: actions/upload-artifact@v4
      with:
        name: cmake-android32
        path: build/install/bin/