name: Build CMake for Android (armeabi-v7a)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_NDK_VERSION: "26.3.11579264"
      ANDROID_PLATFORM: "android-34"
      ANDROID_ABI: "armeabi-v7a"
      BUILD_DIR: "/home/runner/work/Arm/Arm/cmake-build"
      SRC_DIR: "/home/runner/work/Arm/Arm/cmake-src"
      INSTALL_DIR: "/home/runner/work/Arm/Arm/cmake-android-arm-out"

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake make git wget unzip patch
          sudo apt-get clean

      # Step 3: Setup Android SDK and NDK
      - name: Set up Android SDK and NDK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          mkdir -p "$ANDROID_SDK_ROOT"
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip -q tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools-temp
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
          mv $ANDROID_SDK_ROOT/cmdline-tools-temp/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/
          rm -rf $ANDROID_SDK_ROOT/cmdline-tools-temp tools.zip
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"
          yes | sdkmanager --licenses
          yes | sdkmanager --update
          yes | sdkmanager "platforms;${ANDROID_PLATFORM}" "build-tools;34.0.0" "ndk;${ANDROID_NDK_VERSION}"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/${ANDROID_NDK_VERSION}" >> $GITHUB_ENV

      # Step 4: Clone CMake source code
      - name: Clone CMake source code
        run: |
          git clone --depth 1 https://github.com/Kitware/CMake.git ${SRC_DIR}

      # Step 5: Patch pipe.c to replace pipe2 with pipe
      - name: Patch pipe.c for Android compatibility
        run: |
          PIPE_C_PATH="${SRC_DIR}/Utilities/cmlibuv/src/unix/pipe.c"
          if [ -f "$PIPE_C_PATH" ]; then
            sed -i 's/pipe2(temp, flags)/pipe(temp); /* Manually set flags if needed */ /' "$PIPE_C_PATH"
            echo "Patched $PIPE_C_PATH successfully."
          else
            echo "Error: File $PIPE_C_PATH not found!" && exit 1
          fi

      # Step 6: Clean build directory (optional but recommended)
      - name: Clean build directory
        run: |
          if [ -d "${BUILD_DIR}" ]; then
            echo "Cleaning build directory..."
            rm -rf "${BUILD_DIR}"
          fi
          mkdir -p "${BUILD_DIR}"

      # Step 7: Configure CMake for Android
      - name: Configure CMake for Android
        run: |
          cd ${BUILD_DIR}
          cmake ${SRC_DIR} \
            -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_HOME}/build/cmake/android.toolchain.cmake" \
            -DANDROID_ABI="${ANDROID_ABI}" \
            -DANDROID_PLATFORM="${ANDROID_PLATFORM}" \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_TESTING=OFF

      # Step 8: Build CMake
      - name: Build CMake
        working-directory: ${{ env.BUILD_DIR }}
        run: cmake --build . -- -j$(nproc)

      # Step 9: Install CMake
      - name: Install CMake
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cmake --install . --prefix ${INSTALL_DIR}
          ls -lhR ${INSTALL_DIR}

      # Step 10: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmake-android-armeabi-v7a
          path: ${{ env.INSTALL_DIR }}